# This file is @generated by `scripts/codegen.py`. Do not edit.
from __future__ import annotations

import datetime as dt
from typing import Annotated, Literal, NamedTuple, TypeVar

from pydantic import BaseModel, Field

from .requests import arequest, request

T = TypeVar("T")
Missing = Annotated[T | None, Field(default=None)]

ACHTransferStatus = Literal["pending", "in_transit", "deposited", "rejected"]
CardStatus = Literal["active", "inactive", "frozen", "canceled"]
CardType = Literal["virtual", "physical"]
CheckDepositStatus = Literal[
    "pending",
    "submitted",
    "manual_submission_required",
    "rejected",
    "returned",
    "deposited",
]
CheckStatus = Literal[
    "scheduled",
    "in_transit",
    "in_transit_and_processed",
    "deposited",
    "canceled",
    "voided",
    "refunded",
]
DonationStatus = Literal["pending", "in_transit", "deposited", "failed", "refunded"]
HCBFeeStatus = Literal["pending", "in_transit", "settled"]
InvoiceStatus = Literal["open", "paid", "void"]
OrganizationCategory = Literal[
    "hack_club_hq", "robotics_team", "hackathon", "hack_club", "climate", "nonprofit"
]
ReimbursedExpenseStatus = Literal["pending", "in_transit", "settled", "reversed"]
TransactionType = Literal[
    "invoice",
    "donation",
    "ach_transfer",
    "check",
    "transfer",
    "bank_account_transaction",
    "card_charge",
    "wire_transfer",
    "wise_transfer",
    "check_deposit",
    "reimbursed_expense",
    "hcb_fee",
]
TransferStatus = Literal[
    "fulfilled",
    "processing",
    "rejected",
    "canceled",
    "errored",
    "under_review",
    "pending",
]
WireTransferStatus = Literal["pending", "approved", "rejected", "deposited", "failed"]
WiseTransferStatus = Literal[
    "pending", "approved", "rejected", "sent", "deposited", "failed"
]


class Beneficiary(NamedTuple):
    name: str | None


class DonationDonor(NamedTuple):
    name: str | None
    anonymous: bool | None
    avatar: str | None


class InvoiceSponsor(NamedTuple):
    id: str | None
    name: str | None


class OrganizationBalances(NamedTuple):
    balance_cents: int | None
    fee_balance_cents: int | None
    incoming_balance_cents: int | None
    total_raised: int | None


class TransactionComments(BaseModel):
    count: int | None


class TransactionReceipts(BaseModel):
    count: int | None
    missing: bool | None


class ACHTransfer(BaseModel):
    """ACH Transfer model"""

    id: str
    object: Literal["ach_transfer"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[str]
    date: Missing[dt.datetime]
    status: Missing[ACHTransferStatus]
    beneficiary: Missing[Beneficiary]
    user: Missing[User]


class Activity(BaseModel):
    """Activity model"""

    id: str
    object: Literal["activity"]
    href: str
    key: str
    created_at: dt.datetime
    organization: Missing[Organization]
    user: Missing[User]
    transaction: Missing[Transaction]


class Card(BaseModel):
    """Card model"""

    id: str
    object: Literal["card"]
    href: str
    name: Missing[str]
    type: Missing[CardType]
    status: Missing[CardStatus]
    issued_at: Missing[dt.datetime]
    owner: Missing[User]
    organization: Missing[Organization]


class CardCharge(BaseModel):
    """Card Charge model"""

    id: str
    object: Literal["card_charge"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    date: Missing[dt.datetime]
    card: Missing[Card]
    user: Missing[User]


class Check(BaseModel):
    """Check model"""

    id: str
    object: Literal["check"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    date: Missing[dt.datetime]
    status: Missing[CheckStatus]


class CheckDeposit(BaseModel):
    """Check Deposit model"""

    id: str
    object: Literal["check_deposit"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    date: Missing[dt.datetime]
    status: Missing[CheckDepositStatus]
    user: Missing[User]


class Donation(BaseModel):
    """Donation model"""

    id: str
    object: Literal["donation"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    donor: Missing[DonationDonor]
    date: Missing[dt.datetime]
    status: Missing[DonationStatus]
    recurring: Missing[bool]


class HCBFee(BaseModel):
    """HCB Fee model"""

    id: str
    object: Literal["hcb_fee"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    date: Missing[dt.datetime]
    status: Missing[HCBFeeStatus]


class Invoice(BaseModel):
    """Invoice model"""

    id: str
    object: Literal["invoice"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[str]
    sponsor: Missing[InvoiceSponsor]
    date: Missing[dt.datetime]
    status: Missing[InvoiceStatus]


class Organization(BaseModel):
    """Organization model"""

    id: str
    object: Literal["organization"]
    href: str
    name: Missing[str]
    slug: Missing[str]
    website: Missing[str]
    category: Missing[OrganizationCategory]
    transparent: Missing[bool]
    demo_mode: Missing[bool]
    financially_frozen: Missing[bool]
    logo: Missing[str]
    donation_header: Missing[str]
    background_image: Missing[str]
    public_message: Missing[str]
    donation_link: Missing[str]
    balances: Missing[OrganizationBalances]
    created_at: Missing[dt.datetime]
    users: Missing[list[User]]

    async def async_get_transactions(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Transaction]:
        """List an organization's transactions

        Transaction represent a line item on an Organization's ledger. There are various
        types of transaction (see the type below).

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_transactions(
            self.id, expand, page, per_page, offset
        )

    def get_transactions(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Transaction]:
        """List an organization's transactions

        Transaction represent a line item on an Organization's ledger. There are various
        types of transaction (see the type below).

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_transactions(self.id, expand, page, per_page, offset)

    async def async_get_card_charges(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[CardCharge]:
        """List an organization's card charges

        Transactions created using an HCB card.

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_card_charges(
            self.id, expand, page, per_page, offset
        )

    def get_card_charges(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[CardCharge]:
        """List an organization's card charges

        Transactions created using an HCB card.

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_card_charges(self.id, expand, page, per_page, offset)

    async def async_get_donations(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Donation]:
        """List an organization's donations

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_donations(
            self.id, expand, page, per_page, offset
        )

    def get_donations(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Donation]:
        """List an organization's donations

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_donations(self.id, expand, page, per_page, offset)

    async def async_get_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Transfer]:
        """List an organization's transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_transfers(
            self.id, expand, page, per_page, offset
        )

    def get_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Transfer]:
        """List an organization's transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_transfers(self.id, expand, page, per_page, offset)

    async def async_get_wire_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[WireTransfer]:
        """List an organization's wire transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_wire_transfers(
            self.id, expand, page, per_page, offset
        )

    def get_wire_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[WireTransfer]:
        """List an organization's wire transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_wire_transfers(self.id, expand, page, per_page, offset)

    async def async_get_wise_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[WiseTransfer]:
        """List an organization's Wise transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_wise_transfers(
            self.id, expand, page, per_page, offset
        )

    def get_wise_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[WiseTransfer]:
        """List an organization's Wise transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_wise_transfers(self.id, expand, page, per_page, offset)

    async def async_get_check_deposits(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[CheckDeposit]:
        """List an organization's check deposits

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_check_deposits(
            self.id, expand, page, per_page, offset
        )

    def get_check_deposits(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[CheckDeposit]:
        """List an organization's check deposits

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_check_deposits(self.id, expand, page, per_page, offset)

    async def async_get_reimbursed_expenses(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[ReimbursedExpense]:
        """List an organization's reimbursed expenses

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_reimbursed_expenses(
            self.id, expand, page, per_page, offset
        )

    def get_reimbursed_expenses(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[ReimbursedExpense]:
        """List an organization's reimbursed expenses

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_reimbursed_expenses(
            self.id, expand, page, per_page, offset
        )

    async def async_get_hcb_fees(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[HCBFee]:
        """List an organization's HCB fees

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_hcb_fees(
            self.id, expand, page, per_page, offset
        )

    def get_hcb_fees(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[HCBFee]:
        """List an organization's HCB fees

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_hcb_fees(self.id, expand, page, per_page, offset)

    async def async_get_invoices(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Invoice]:
        """List an organization's invoices

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_invoices(
            self.id, expand, page, per_page, offset
        )

    def get_invoices(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Invoice]:
        """List an organization's invoices

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_invoices(self.id, expand, page, per_page, offset)

    async def async_get_ach_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[ACHTransfer]:
        """List an organization's ACH transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_ach_transfers(
            self.id, expand, page, per_page, offset
        )

    def get_ach_transfers(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[ACHTransfer]:
        """List an organization's ACH transfers

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_ach_transfers(self.id, expand, page, per_page, offset)

    async def async_get_checks(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Check]:
        """List an organization's checks

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_checks(
            self.id, expand, page, per_page, offset
        )

    def get_checks(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Check]:
        """List an organization's checks

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_checks(self.id, expand, page, per_page, offset)

    async def async_get_cards(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Card]:
        """List an organization's cards

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return await async_get_organization_cards(
            self.id, expand, page, per_page, offset
        )

    def get_cards(
        self,
        expand: str | None = None,
        page: int | None = None,
        per_page: int | None = None,
        offset: int | None = None,
    ) -> list[Card]:
        """List an organization's cards

        expand (str): Object types to expand in the API response (separated by commas)
        page (int): Page offset to fetch. (defaults to 1)
        per_page (int): Number of results to return per page. (defaults to 50)
        offset (int): Pad a number of results. (defaults to 0)
        """
        return get_organization_cards(self.id, expand, page, per_page, offset)


class ReimbursedExpense(BaseModel):
    """Reimbursed Expense model"""

    id: str
    object: Literal["reimbursed_expense"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    date: Missing[dt.datetime]
    status: Missing[ReimbursedExpenseStatus]


class Tag(BaseModel):
    id: str
    object: Literal["tag"]
    label: str


class Transaction(BaseModel):
    """Transaction model"""

    id: str
    object: Literal["transaction"]
    href: str
    amount_cents: Missing[int]
    memo: Missing[str]
    date: Missing[dt.datetime]
    type: Missing[TransactionType]
    pending: Missing[bool]
    receipts: Missing[TransactionReceipts]
    comments: Missing[TransactionComments]
    organization: Missing[Organization]
    user: Missing[User]
    tags: Missing[list[Tag]]
    card_charge: Missing[CardCharge]
    ach_transfer: Missing[ACHTransfer]
    check: Missing[Check]
    donation: Missing[Donation]
    invoice: Missing[Invoice]
    transfer: Missing[Transfer]
    wire_transfer: Missing[WireTransfer]
    wise_transfer: Missing[WiseTransfer]
    check_deposit: Missing[CheckDeposit]
    reimbursed_expense: Missing[ReimbursedExpense]
    hcb_fee: Missing[HCBFee]


class Transfer(BaseModel):
    """Transfer model"""

    id: str
    object: Literal["transfer"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[str]
    date: Missing[dt.datetime]
    status: Missing[TransferStatus]
    source_organization: Missing[Organization]


class User(BaseModel):
    id: str
    object: Literal["user"]
    full_name: str
    auditor: bool
    admin: bool
    photo: str


class WireTransfer(BaseModel):
    """Wire Transfer model"""

    id: str
    object: Literal["wire_transfer"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    local_currency: Missing[str]
    local_amount_cents: Missing[int]
    date: Missing[dt.datetime]
    status: Missing[WireTransferStatus]
    beneficiary: Missing[Beneficiary]
    user: Missing[User]


class WiseTransfer(BaseModel):
    """Wise Transfer model"""

    id: str
    object: Literal["wise_transfer"]
    href: str
    memo: Missing[str]
    transaction: Missing[Transaction]
    organization: Missing[Organization]
    amount_cents: Missing[int]
    local_currency: Missing[str]
    local_amount_cents: Missing[int]
    date: Missing[dt.datetime]
    status: Missing[WiseTransferStatus]
    beneficiary: Missing[Beneficiary]
    user: Missing[User]


_ = ACHTransfer.model_rebuild()
_ = Activity.model_rebuild()
_ = Card.model_rebuild()
_ = CardCharge.model_rebuild()
_ = Check.model_rebuild()
_ = CheckDeposit.model_rebuild()
_ = Donation.model_rebuild()
_ = HCBFee.model_rebuild()
_ = Invoice.model_rebuild()
_ = Organization.model_rebuild()
_ = ReimbursedExpense.model_rebuild()
_ = Tag.model_rebuild()
_ = Transaction.model_rebuild()
_ = Transfer.model_rebuild()
_ = User.model_rebuild()
_ = WireTransfer.model_rebuild()
_ = WiseTransfer.model_rebuild()


def get_organizations(
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
    expand: str | None = None,
) -> list[Organization]:
    """Get a list of transparent organizations

    Returns a list of organizations in Transparency Mode that have opted in to public
    listing.

    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        "/organizations",
        {"page": page, "per_page": per_page, "offset": offset, "expand": expand},
        list[Organization],
    )


async def async_get_organizations(
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
    expand: str | None = None,
) -> list[Organization]:
    """Get a list of transparent organizations

    Returns a list of organizations in Transparency Mode that have opted in to public
    listing.

    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        "/organizations",
        {"page": page, "per_page": per_page, "offset": offset, "expand": expand},
        list[Organization],
    )


def get_organization(organization_id: str, expand: str | None = None) -> Organization:
    """Get a single organization

    The organization must be in Transparency Mode.

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        f"/organizations/{organization_id}", {"expand": expand}, Organization
    )


async def async_get_organization(
    organization_id: str, expand: str | None = None
) -> Organization:
    """Get a single organization

    The organization must be in Transparency Mode.

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/organizations/{organization_id}", {"expand": expand}, Organization
    )


def get_organization_transactions(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Transaction]:
    """List an organization's transactions

    Transaction represent a line item on an Organization's ledger. There are various
    types of transaction (see the type below).

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/transactions",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Transaction],
    )


async def async_get_organization_transactions(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Transaction]:
    """List an organization's transactions

    Transaction represent a line item on an Organization's ledger. There are various
    types of transaction (see the type below).

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/transactions",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Transaction],
    )


def get_organization_card_charges(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[CardCharge]:
    """List an organization's card charges

    Transactions created using an HCB card.

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/card_charges",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[CardCharge],
    )


async def async_get_organization_card_charges(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[CardCharge]:
    """List an organization's card charges

    Transactions created using an HCB card.

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/card_charges",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[CardCharge],
    )


def get_organization_donations(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Donation]:
    """List an organization's donations

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/donations",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Donation],
    )


async def async_get_organization_donations(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Donation]:
    """List an organization's donations

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/donations",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Donation],
    )


def get_organization_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Transfer]:
    """List an organization's transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Transfer],
    )


async def async_get_organization_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Transfer]:
    """List an organization's transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Transfer],
    )


def get_organization_wire_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[WireTransfer]:
    """List an organization's wire transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/wire_transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[WireTransfer],
    )


async def async_get_organization_wire_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[WireTransfer]:
    """List an organization's wire transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/wire_transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[WireTransfer],
    )


def get_organization_wise_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[WiseTransfer]:
    """List an organization's Wise transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/wise_transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[WiseTransfer],
    )


async def async_get_organization_wise_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[WiseTransfer]:
    """List an organization's Wise transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/wise_transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[WiseTransfer],
    )


def get_organization_check_deposits(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[CheckDeposit]:
    """List an organization's check deposits

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/check_deposits",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[CheckDeposit],
    )


async def async_get_organization_check_deposits(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[CheckDeposit]:
    """List an organization's check deposits

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/check_deposits",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[CheckDeposit],
    )


def get_organization_reimbursed_expenses(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[ReimbursedExpense]:
    """List an organization's reimbursed expenses

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/reimbursed_expenses",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[ReimbursedExpense],
    )


async def async_get_organization_reimbursed_expenses(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[ReimbursedExpense]:
    """List an organization's reimbursed expenses

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/reimbursed_expenses",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[ReimbursedExpense],
    )


def get_organization_hcb_fees(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[HCBFee]:
    """List an organization's HCB fees

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/hcb_fees",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[HCBFee],
    )


async def async_get_organization_hcb_fees(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[HCBFee]:
    """List an organization's HCB fees

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/hcb_fees",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[HCBFee],
    )


def get_organization_invoices(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Invoice]:
    """List an organization's invoices

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/invoices",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Invoice],
    )


async def async_get_organization_invoices(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Invoice]:
    """List an organization's invoices

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/invoices",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Invoice],
    )


def get_organization_ach_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[ACHTransfer]:
    """List an organization's ACH transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/ach_transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[ACHTransfer],
    )


async def async_get_organization_ach_transfers(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[ACHTransfer]:
    """List an organization's ACH transfers

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/ach_transfers",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[ACHTransfer],
    )


def get_organization_checks(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Check]:
    """List an organization's checks

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/checks",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Check],
    )


async def async_get_organization_checks(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Check]:
    """List an organization's checks

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/checks",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Check],
    )


def get_organization_cards(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Card]:
    """List an organization's cards

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return request(
        f"/organizations/{organization_id}/cards",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Card],
    )


async def async_get_organization_cards(
    organization_id: str,
    expand: str | None = None,
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
) -> list[Card]:
    """List an organization's cards

    organization_id (str): Organization ID or slug.
    expand (str): Object types to expand in the API response (separated by commas)
    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    """
    return await arequest(
        f"/organizations/{organization_id}/cards",
        {"expand": expand, "page": page, "per_page": per_page, "offset": offset},
        list[Card],
    )


def get_card_charge(card_charge_id: str, expand: str | None = None) -> CardCharge:
    """Get a card charge

    card_charge_id (str): Card charge ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/card_charges/{card_charge_id}", {"expand": expand}, CardCharge)


async def async_get_card_charge(
    card_charge_id: str, expand: str | None = None
) -> CardCharge:
    """Get a card charge

    card_charge_id (str): Card charge ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/card_charges/{card_charge_id}", {"expand": expand}, CardCharge
    )


def get_donation(donation_id: str, expand: str | None = None) -> Donation:
    """Get a single donation

    donation_id (str): Donation ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/donations/{donation_id}", {"expand": expand}, Donation)


async def async_get_donation(donation_id: str, expand: str | None = None) -> Donation:
    """Get a single donation

    donation_id (str): Donation ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/donations/{donation_id}", {"expand": expand}, Donation)


def get_transfer(transfer_id: str, expand: str | None = None) -> Transfer:
    """Get a single transfer

    transfer_id (str): Transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/transfers/{transfer_id}", {"expand": expand}, Transfer)


async def async_get_transfer(transfer_id: str, expand: str | None = None) -> Transfer:
    """Get a single transfer

    transfer_id (str): Transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/transfers/{transfer_id}", {"expand": expand}, Transfer)


def get_wire_transfer(wire_transfer_id: str, expand: str | None = None) -> WireTransfer:
    """Get a single wire transfer

    wire_transfer_id (str): Wire transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        f"/wire_transfers/{wire_transfer_id}", {"expand": expand}, WireTransfer
    )


async def async_get_wire_transfer(
    wire_transfer_id: str, expand: str | None = None
) -> WireTransfer:
    """Get a single wire transfer

    wire_transfer_id (str): Wire transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/wire_transfers/{wire_transfer_id}", {"expand": expand}, WireTransfer
    )


def get_wise_transfer(wise_transfer_id: str, expand: str | None = None) -> WiseTransfer:
    """Get a single Wise transfer

    wise_transfer_id (str): Wise transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        f"/wise_transfers/{wise_transfer_id}", {"expand": expand}, WiseTransfer
    )


async def async_get_wise_transfer(
    wise_transfer_id: str, expand: str | None = None
) -> WiseTransfer:
    """Get a single Wise transfer

    wise_transfer_id (str): Wise transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/wise_transfers/{wise_transfer_id}", {"expand": expand}, WiseTransfer
    )


def get_check_deposit(check_deposit_id: str, expand: str | None = None) -> CheckDeposit:
    """Get a single check deposit

    check_deposit_id (str): Check deposit ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        f"/check_deposits/{check_deposit_id}", {"expand": expand}, CheckDeposit
    )


async def async_get_check_deposit(
    check_deposit_id: str, expand: str | None = None
) -> CheckDeposit:
    """Get a single check deposit

    check_deposit_id (str): Check deposit ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/check_deposits/{check_deposit_id}", {"expand": expand}, CheckDeposit
    )


def get_reimbursed_expense(
    reimbursed_expense_id: str, expand: str | None = None
) -> ReimbursedExpense:
    """Get a single reimbursed expense

    reimbursed_expense_id (str): Reimbursed expense ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        f"/reimbursed_expenses/{reimbursed_expense_id}",
        {"expand": expand},
        ReimbursedExpense,
    )


async def async_get_reimbursed_expense(
    reimbursed_expense_id: str, expand: str | None = None
) -> ReimbursedExpense:
    """Get a single reimbursed expense

    reimbursed_expense_id (str): Reimbursed expense ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/reimbursed_expenses/{reimbursed_expense_id}",
        {"expand": expand},
        ReimbursedExpense,
    )


def get_hcb_fee(hcb_fee_id: str, expand: str | None = None) -> HCBFee:
    """Get a single HCB fee

    hcb_fee_id (str): HCB fee ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/hcb_fees/{hcb_fee_id}", {"expand": expand}, HCBFee)


async def async_get_hcb_fee(hcb_fee_id: str, expand: str | None = None) -> HCBFee:
    """Get a single HCB fee

    hcb_fee_id (str): HCB fee ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/hcb_fees/{hcb_fee_id}", {"expand": expand}, HCBFee)


def get_invoice(invoice_id: str, expand: str | None = None) -> Invoice:
    """Get a single invoice

    invoice_id (str): Invoice ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/invoices/{invoice_id}", {"expand": expand}, Invoice)


async def async_get_invoice(invoice_id: str, expand: str | None = None) -> Invoice:
    """Get a single invoice

    invoice_id (str): Invoice ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/invoices/{invoice_id}", {"expand": expand}, Invoice)


def get_ach_transfer(ach_transfer_id: str, expand: str | None = None) -> ACHTransfer:
    """Get a single ACH transfer

    ach_transfer_id (str): ACH transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/ach_transfers/{ach_transfer_id}", {"expand": expand}, ACHTransfer)


async def async_get_ach_transfer(
    ach_transfer_id: str, expand: str | None = None
) -> ACHTransfer:
    """Get a single ACH transfer

    ach_transfer_id (str): ACH transfer ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/ach_transfers/{ach_transfer_id}", {"expand": expand}, ACHTransfer
    )


def get_check(check_id: str, expand: str | None = None) -> Check:
    """Get a single check

    check_id (str): Check ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/checks/{check_id}", {"expand": expand}, Check)


async def async_get_check(check_id: str, expand: str | None = None) -> Check:
    """Get a single check

    check_id (str): Check ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/checks/{check_id}", {"expand": expand}, Check)


def get_card(card_id: str, expand: str | None = None) -> Card:
    """Get a single card

    card_id (str): Card ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/cards/{card_id}", {"expand": expand}, Card)


async def async_get_card(card_id: str, expand: str | None = None) -> Card:
    """Get a single card

    card_id (str): Card ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/cards/{card_id}", {"expand": expand}, Card)


def get_transaction(transaction_id: str, expand: str | None = None) -> Transaction:
    """Get a single transaction

    transaction_id (str): Transaction ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/transactions/{transaction_id}", {"expand": expand}, Transaction)


async def async_get_transaction(
    transaction_id: str, expand: str | None = None
) -> Transaction:
    """Get a single transaction

    transaction_id (str): Transaction ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        f"/transactions/{transaction_id}", {"expand": expand}, Transaction
    )


def get_activities(
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
    expand: str | None = None,
) -> list[Activity]:
    """Get a list of recent activities on transparent HCB organizations

    Returns a list of recent activities from all HCB organizations that are in
    Transparency Mode and have opted in to public listing.

    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(
        "/activities",
        {"page": page, "per_page": per_page, "offset": offset, "expand": expand},
        list[Activity],
    )


async def async_get_activities(
    page: int | None = None,
    per_page: int | None = None,
    offset: int | None = None,
    expand: str | None = None,
) -> list[Activity]:
    """Get a list of recent activities on transparent HCB organizations

    Returns a list of recent activities from all HCB organizations that are in
    Transparency Mode and have opted in to public listing.

    page (int): Page offset to fetch. (defaults to 1)
    per_page (int): Number of results to return per page. (defaults to 50)
    offset (int): Pad a number of results. (defaults to 0)
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(
        "/activities",
        {"page": page, "per_page": per_page, "offset": offset, "expand": expand},
        list[Activity],
    )


def get_activity(activity_id: str, expand: str | None = None) -> Activity:
    """Get a single activity

    activity_id (str): Activity ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return request(f"/activities/{activity_id}", {"expand": expand}, Activity)


async def async_get_activity(activity_id: str, expand: str | None = None) -> Activity:
    """Get a single activity

    activity_id (str): Activity ID
    expand (str): Object types to expand in the API response (separated by commas)
    """
    return await arequest(f"/activities/{activity_id}", {"expand": expand}, Activity)
