from __future__ import annotations

import re
from itertools import chain, product
from pathlib import Path
from textwrap import indent, wrap
from typing import TYPE_CHECKING, Any, TypeAlias

import httpx

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator

API_SWAGGER_DOC = httpx.get("https://hcb.hackclub.com/api/v3/swagger_doc").json()

Param: TypeAlias = "tuple[str, str, str, str | int | None]"

ROOT_DIR = Path(__file__).parents[1]
MODULE = ROOT_DIR / "src" / "hcb"

ENDPOINT_TEMPLATE = """
def get_{name}({params}) -> {ret_type}:
{docstring}
    return request({path}, {query}, {ret_type})


async def async_get_{name}({params}) -> {ret_type}:
{docstring}
    return await arequest({path}, {query}, {ret_type})
"""

MODELS = (
    "ACHTransfer",
    "Activity",
    "Card",
    "CardCharge",
    "Check",
    "CheckDeposit",
    "Donation",
    "HCBFee",
    "Invoice",
    "Organization",
    "ReimbursedExpense",
    "Tag",
    "Transaction",
    "Transfer",
    "User",
    "WireTransfer",
    "WiseTransfer",
)

CODEGEN_NOTE = "# This file is @generated by `scripts/codegen.py`. Do not edit."

HEADING = f"""{CODEGEN_NOTE}
from __future__ import annotations

import datetime as dt
from typing import Annotated, Literal, NamedTuple, TypeVar

from pydantic import BaseModel, Field

from .requests import arequest, request

T = TypeVar("T")
Missing = Annotated[T | None, Field(default=None)]

"""

TRANSPARENCY_MODE_REPLACEMENT = (
    "<a href='https://blog.hcb.hackclub.com/posts/transparent-finances-optional-feature"
    "-151427'><strong>Transparency Mode</strong></a>",
    "Transparency Mode",
)

START_ANCHOR = "# @@@ codegen-start"
END_ANCHOR = "# @@@ codegen-start"

ORGANIZATION_METHOD_TEMPLATE = """
    async def async_get_{name}(self, {params}) -> {ret_type}:
    {docstring}
        return await async_get_organization_{name}(self.id, {query})

    def get_{name}(self, {params}) -> {ret_type}:
    {docstring}
        return get_organization_{name}(self.id, {query})
"""


def endpoint_data() -> Iterator[tuple[str, str]]:
    for path in API_SWAGGER_DOC["paths"]:
        if "{organization_id}" in path:
            name = "organization"
            if path.endswith("s"):
                *_, items = path.rpartition("/")
                name += f"_{items}"
        elif path.endswith("s"):
            *_, name = path.rpartition("/")
        elif path.endswith("}"):
            name = path[path.find("{") + 1 :].removesuffix("_id}")
        else:
            raise RuntimeError(path)
        yield name, path


def format_docstring(
    summary: str,
    description: str,
    parameters: Iterable[Param],
) -> str:
    description = description.replace(*TRANSPARENCY_MODE_REPLACEMENT)
    for fmt, tag in product(("<{}>", "</{}>", "<{}/>"), ("em", "br")):
        description = description.replace(fmt.format(tag), "")
    params = "\n".join(
        # string and integer are the only types present in
        f"{name} ({'str' if type_ == 'string' else 'int'}): {desc}"
        + (f" (defaults to {default})" * (default is not None))
        for name, desc, type_, default in parameters
    )
    desc = "\n".join(["", *wrap(description, 84), ""]) if description else ""
    base = f"{summary}\n{desc}\n{params}".strip()
    fence = '    """'
    return f"{fence}{indent(base, '    ').lstrip()}\n{fence}"


def format_params(path_param: Param | None, optionals: Iterable[Param]) -> str:
    opt_params = (
        f"{name}: {type_[:3]} | None = None" for name, _, type_, _ in optionals
    )
    if path_param is None:
        return ", ".join(opt_params)
    name, _, type_, _ = path_param
    return ", ".join(chain((f"{name}: {type_[:3]}",), opt_params))


def get_return_type(name: str) -> str:
    ret_list = name.endswith("s")
    name = name.removesuffix("s").removeprefix("organization_")
    name = name.title().replace("_", "")

    # Special cases
    if name.startswith(("Hcb", "Ach")):
        name = f"{name[:3].upper()}{name[3:]}"
    if name == "Activitie":
        name = "Activity"

    return f"list[{name}]" if ret_list else name


def resolve_params(params_: list[dict[str, Any]]) -> tuple[list[Param], Param | None]:
    params = [
        (p["name"], p["description"], p["type"], p.get("default")) for p in params_
    ]
    path_param = next(
        (
            (name, desc, type_, default)
            for name, desc, type_, default in params
            if default is None and name != "expand"
        ),
        None,
    )
    if path_param is not None:
        params.remove(path_param)
    return params, path_param


def generate_endpoint(name: str, path: str) -> str:
    ep = API_SWAGGER_DOC["paths"][path]["get"]
    path = path.removeprefix("/api/v3")
    params, path_param = resolve_params(ep["parameters"])
    return ENDPOINT_TEMPLATE.format(
        name=name,
        params=format_params(path_param, params),
        docstring=format_docstring(
            ep["summary"],
            ep["description"],
            (path_param, *params) if path_param else params,
        ),
        path=f'f"{path}"' if path_param else path.join('""'),
        ret_type=get_return_type(name),
        query=", ".join(f'"{p}": {p}' for p, *_ in params).join("{}"),
    )


def generate_endpoint_impls() -> str:
    return "\n".join(generate_endpoint(name, path) for name, path in endpoint_data())


def endpoint_function_names() -> list[str]:
    return sorted(
        chain.from_iterable(
            (f"get_{name}", f"async_get_{name}") for name, _ in endpoint_data()
        )
    )


def codegen_init() -> None:
    names = sorted((*MODELS, *endpoint_function_names()))
    imports = f"from .core import {', '.join(names)}"
    err_import = "from .requests import HCBAPIError"
    names.append("HCBAPIError")
    names.sort()
    dunder_all = f"__all__ = ({', '.join(map(repr, names))})"
    content = f"{CODEGEN_NOTE}\n{imports}\n{err_import}\n{dunder_all}"
    _ = (MODULE / "__init__.py").write_text(content)


def collect_types() -> tuple[
    dict[str, Any], dict[str, list[str]], dict[str, dict[str, str]]
]:
    enums: dict[str, list[str]] = {}
    custom_types: dict[str, dict[str, str]] = {"Beneficiary": {"name": "str"}}
    types: dict[str, dict[str, Any]] = {}
    for def_name, definition in API_SWAGGER_DOC.get("definitions", {}).items():
        if def_name == "Error Response":
            continue
        class_name = def_name.replace(" ", "")
        types[class_name] = definition
        for prop_name, prop in definition.get("properties", {}).items():
            type_name = class_name + prop_name.capitalize()
            if enum := prop.get("enum"):
                enums[type_name] = enum
                continue
            if prop.get("type") != "object" or prop_name == "beneficiary":
                continue
            custom_types[type_name] = {
                k: infer_python_type(v, prop_name, class_name)
                for k, v in prop["properties"].items()
            }
    return types, enums, custom_types


def generate_literal(name: str, values: list[str]) -> str:
    return f"{name} = Literal[{', '.join(map(repr, values))}]"


def infer_python_type(prop: dict[str, Any], field_name: str, class_name: str) -> str:  # noqa: PLR0911
    if field_name == "beneficiary":
        return "Beneficiary"
    if (field_type := prop.get("type", "")) == "object" or "enum" in prop:
        return class_name + field_name.capitalize()
    if field_type == "array":
        items_type = infer_python_type(prop["items"], field_name, class_name)
        return f"list[{items_type}]"
    if ref := prop.get("$ref"):
        return ref.rpartition("/")[-1].replace(" ", "")
    if field_type == "boolean":
        return "bool"
    if field_type == "string" and (field_name == "date" or field_name.endswith("_at")):
        return "dt.datetime"
    return field_type[:3]


def get_object_literal_value(class_name: str) -> str:
    s1 = re.sub("([A-Z]+)([A-Z][a-z]+)", r"\1_\2", class_name)
    return re.sub("([a-z])([A-Z])", r"\1_\2", s1).casefold()


def generate_custom_class(name: str, fields: dict[str, str]) -> str:
    parent = "BaseModel" if "count" in fields else "NamedTuple"
    fields_str = "\n".join(f"    {name}: {typ} | None" for name, typ in fields.items())
    return f"class {name}({parent}):\n{fields_str}"


def generate_organization_methods(lines: list[str]) -> None:
    for name_, path in endpoint_data():
        if "organization_" not in name_:
            continue
        name = name_.removeprefix("organization_")
        ep = API_SWAGGER_DOC["paths"][path]["get"]
        params, path_param = resolve_params(ep["parameters"])
        if path_param and path_param[0] == "organization_id":
            path_param = None
        lines.append(
            ORGANIZATION_METHOD_TEMPLATE.format(
                name=name,
                docstring=format_docstring(
                    ep["summary"],
                    ep["description"],
                    (path_param, *params) if path_param else params,
                ),
                params=format_params(path_param, params),
                ret_type=get_return_type(name),
                query=", ".join(p for p, *_ in params),
            )
        )


def generate_basemodel(name: str, definition: dict[str, Any]) -> str:
    lines = [f"class {name}(BaseModel):"]
    if description := definition.get("description"):
        lines.append(f'    """{description}"""')

    for prop_name, prop in definition.get("properties", {}).items():
        if prop_name == "object":
            prop_type = f'Literal["{get_object_literal_value(name)}"]'
        else:
            prop_type = infer_python_type(prop, prop_name, name)

        if prop_name not in definition.get("required", ()):
            prop_type = f"Missing[{prop_type}]"
        lines.append(f"    {prop_name}: {prop_type}")

    if name == "Organization":
        generate_organization_methods(lines)

    return "\n".join(lines)


def generate_models() -> str:
    types, literals, objects = collect_types()
    return "\n".join(
        chain(
            (generate_literal(*entry) for entry in sorted(literals.items())),
            (generate_custom_class(*entry) for entry in sorted(objects.items())),
            (generate_basemodel(*entry) for entry in sorted(types.items())),
            (f"_ = {model}.model_rebuild()" for model in MODELS),
        )
    )


def codegen_models_and_endpoints() -> None:
    _ = (MODULE / "core.py").write_text(
        HEADING + generate_models() + generate_endpoint_impls()
    )


if __name__ == "__main__":
    codegen_models_and_endpoints()
    codegen_init()
